# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50525810d7c68977b1dd2cdb34939ad63671cd22e8f94f91203bbfa86248cdc8f1e8c00361fd1bb4ffb9417e587e0d365a9a5a00f937af43cfed810a3999f490

test:
  secret_key_base: f903e9a71d5e582bcc3f2fd48d583c0b5c06138fe9af2cb33d0ccfc27189372af986d877e28d55ac54a2e7ddb95cef7901ed11f36e1f995df8196a5ac616a513

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
